name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
          
      - name: Install Dependencies
        run: |
          npm install
          cd functions && npm install
        
      # - name: Build
      #   run: |
      #     npm run build
      #     cd functions && npm run build
        
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FB_TOOLS_DEV }}
          channelId: live
          projectId: fb-tools-dev
          target: site
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
